// @ts-check
/**
 * ONE ESLint flat config for the whole monorepo.
 *
 * Run from the repo root: `npx eslint . --max-warnings 0` (CI gate).
 *
 * Deliberately NOT the type-checked typescript-eslint preset: it re-runs the
 * TypeScript program per file (slow), and every workspace already runs `tsc`
 * in strict mode in CI. This config catches what tsc does not (unused code,
 * `any`, hook rules, Next.js pitfalls) and stays fast.
 */
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';
import { fileURLToPath } from 'node:url';

// Absolute, so the Next rules resolve the app/ directory the same whether
// ESLint runs from the repo root (CI) or from almond-web/ (`next build`).
const WEB_ROOT = fileURLToPath(new URL('./almond-web/', import.meta.url));

export default defineConfig(
  // ── What is never linted ───────────────────────────────────────────────
  globalIgnores(
    [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      'playwright-report/**',
      'test-results/**',
      'blob-report/**',
      'almond-app/.expo/**',
      'almond-app/public/**',
      'almond-web/public/**',
      // Generated — rewritten by `npm run menu:pull`; fix the generator, not the output.
      '**/menu.generated.ts',
      // Generated by Next.js on every build/dev run.
      'almond-web/next-env.d.ts',
      // Prose with illustrative code snippets for partners (Ishbek), not
      // shipped or compiled by any workspace.
      'docs/**',
    ],
    'almond/ignores',
  ),

  // ── Base: every JS/TS file ─────────────────────────────────────────────
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    // Registered globally but with NO rules here: `next build` (run from
    // almond-web/) detects the Next plugin by resolving the config for THIS
    // file, and warns "Next.js plugin was not detected" otherwise. The
    // @next/next rules are switched on for almond-web only, below.
    name: 'almond/next-plugin-registration',
    plugins: { '@next/next': nextPlugin },
  },
  {
    name: 'almond/base',
    linterOptions: {
      // A disable comment that no longer suppresses anything is dead weight
      // and hides the day the rule starts matching again elsewhere on the line.
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      // Codebase rule: strict TypeScript, no `any`.
      '@typescript-eslint/no-explicit-any': 'error',
      // `_`-prefixed names are the conventional "intentionally unused" marker
      // (positional callback params, destructured-away fields).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
    },
  },

  // ── Node: bff, scripts, e2e, root + workspace config files ─────────────
  {
    name: 'almond/node',
    files: [
      'bff/**/*.{ts,mts,js,mjs}',
      'scripts/**/*.{ts,mts,js,mjs,cjs}',
      'e2e/**/*.ts',
      'playwright.config.ts',
      'eslint.config.mjs',
      '*/vitest.config.ts',
      'almond-web/*.{js,mjs,cjs,ts}',
      'almond-app/*.{js,cjs}',
    ],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    // Expo's babel.config.js / metro.config.js are CommonJS by contract
    // (Metro and Babel `require()` them); `require` is correct there.
    name: 'almond/commonjs-config',
    files: ['almond-app/babel.config.js', 'almond-app/metro.config.js'],
    languageOptions: { sourceType: 'commonjs' },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },

  // ── Shared package: pure TS rules, runs in Node, browser and RN ────────
  {
    name: 'almond/shared',
    files: ['packages/shared/**/*.ts'],
    languageOptions: { globals: { ...globals['shared-node-browser'] } },
  },

  // ── Website (Next.js 15, React 19) ─────────────────────────────────────
  {
    name: 'almond/web',
    files: ['almond-web/**/*.{ts,tsx,js,mjs}'],
    languageOptions: { globals: { ...globals.browser } },
    settings: { next: { rootDir: WEB_ROOT } },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  // ── App (Expo / React Native) ──────────────────────────────────────────
  {
    // RN provides a browser-like global surface (fetch, setTimeout,
    // console, FormData, URL…) plus `__DEV__`; the `browser` set is the
    // closest standard superset, and the `expo-router` web target uses it too.
    name: 'almond/app',
    files: ['almond-app/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, __DEV__: 'readonly' },
    },
    rules: {
      // `require('./logo.png')` / `require('./font.ttf')` is React Native's
      // static-asset idiom: Metro resolves it at bundle time into an asset
      // id, which `<Image source>` and `useFonts` expect. Allow exactly that;
      // a `require()` of code is still an error.
      '@typescript-eslint/no-require-imports': [
        'error',
        { allow: ['\\.(png|jpe?g|gif|webp|ttf|otf)$'] },
      ],
    },
  },

  // ── React hooks (both React surfaces) ──────────────────────────────────
  {
    // Only the two classic rules. The v7 plugin's recommended preset also
    // ships React-Compiler diagnostics (purity, refs, set-state-in-effect…);
    // neither app is compiled with the React Compiler, so those are opt-in
    // later, not a gate now.
    name: 'almond/react-hooks',
    files: ['almond-web/**/*.{ts,tsx}', 'almond-app/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // ── Odoo addon JS (OWL / Odoo asset bundle, browser) ───────────────────
  {
    name: 'almond/odoo-addons',
    files: ['integrations/**/*.js'],
    languageOptions: {
      sourceType: 'module',
      globals: { ...globals.browser, odoo: 'readonly' },
    },
  },

  // ── Tests ──────────────────────────────────────────────────────────────
  {
    // Vitest/Playwright run in Node (fs, path, crypto, process.env).
    // Nothing else is relaxed: `no-explicit-any` stays an error in tests too,
    // and `no-non-null-assertion` (which tests would legitimately need for
    // `map.get(k)!` on fixtures they just built) is not in the recommended
    // preset, so there is nothing to turn off. If a stricter preset is
    // adopted later, relax that rule HERE, for tests only.
    name: 'almond/tests',
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      'bff/test/**/*.ts',
      'e2e/**/*.ts',
    ],
    languageOptions: { globals: { ...globals.node } },
  },
);
